const dbConfig = require("../config/db.config")
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db={};
db.mongoose=mongoose;
db.url=dbConfig.url;
db.users=require("./users.model")(mongoose);
db.centers=require("./centers.model")(mongoose);
db.admins=require("./admins.model")(mongoose);
db.dosagedetails=require("./dosagedetails.model")(mongoose);
module.exports=db